Mylumineyes.Web/Areas/SuperAdmin/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Mylumineyes.Areas.SuperAdmin.Models;
using Mylumineyes.Filters;
using Mylumineyes.Web.database;
using Mylumineyes.Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Mylumineyes.Web.Areas.SuperAdmin.Controllers
{
    //[SuperAdminAuthorize]
    public class DashboardController : Controller
    {
        // GET: SuperAdmin/Dashboard
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;
        private dbMylumineyesEntities dbContext = new dbMylumineyesEntities();
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ActionResult Download(Guid docId, string col)
        {
            try
            {
                var objDoc = dbContext.tblUserDatas.Where(x => x.ID == docId).FirstOrDefault();
                if (objDoc != null)
                {
                    var file = "";
                    if (col == "File1")
                    {
                        file = Server.MapPath("~" + objDoc.File1);
                    }
                    else
                    {
                        file = Server.MapPath("~" + objDoc.File2);
                    }
                    string ext = Path.GetExtension(file);
                    ext = ext.ToLower();
                    var fileName = Path.GetFileName(file);
                    var contentType = GetContentType(ext);
                    return File(file, contentType, fileName);
                }
            }
            catch (Exception ex)
            {
            }
            return View();
        }
        public string GetContentType(string ext)
        {
            string contentType = "";
            try
            {
                switch (ext)
                {
                    case ".jpg":
                        contentType = "image/jpg";
                        break;
                    case ".jpeg":
                        contentType = "image/jpeg";
                        break;
                    case ".pjpeg":
                        contentType = "image/pjpeg";
                        break;
                    case ".gif":
                        contentType = "image/gif";
                        break;
                    case ".x-png":
                        contentType = "image/x-png";
                        break;
                    case ".png":
                        contentType = "image/png";
                        break;
                }
            }
            catch (Exception ex)
            {
            }
            return contentType;
        }
        public ActionResult DeleteRequest(Guid id)
        {
            var Success = false;
            var Message = string.Empty;

            var entity = dbContext.tblUserDatas.Where(x => x.ID == id).FirstOrDefault();
            if (entity != null)
            {
                dbContext.tblUserDatas.Remove(entity);
                dbContext.SaveChanges();
                Success = true;
                Message = "Deleted Successfully";
            }
            else
            {
                Success = false;
                Message = "Record not found";
            }
            return Json(new
            {
                Success = Success,
                Message = Message
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SearchRequests(DateTime? dtFrom, DateTime? dtTo)
        {
            var UserId = User.Identity.GetUserId();
            List<UserDataVM> model = new List<UserDataVM>();
            try
            {
                model = dbContext.tblUserDatas.Where(x => (DbFunctions.TruncateTime(x.CreateDate) >= DbFunctions.TruncateTime(dtFrom.Value) || dtFrom == null) && (DbFunctions.TruncateTime(x.CreateDate) <= DbFunctions.TruncateTime(dtTo.Value) || dtTo == null)).OrderByDescending(x => x.CreateDate).Select(x => new UserDataVM
                {
                    Email = x.Email,
                    File1 = x.File1,
                    File2 = x.File2,
                    FullName = x.FullName,
                    Id = x.ID,
                    Obeservations = x.Obeservations,
                    PhoneNo = x.PhoneNo,
                    CreatedDate = x.CreateDate
                }).ToList();
            }
            catch (Exception ex)
            {

            }
            return PartialView("_RequestData", model);
        }
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordVM model)
        {
            var Success = false;
            var Message = string.Empty;


            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                var userId = User.Identity.GetUserId();
                var result = await UserManager.ChangePasswordAsync(userId, model.OldPassword, model.NewPassword);
                if (result.Succeeded)
                {
                    var user = await UserManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                    }
                    Success = true;
                    Message = "Password Changed Successfully";
                    //   return RedirectToAction("DashBoard", "DashBoard", new { area = "SuperAdmin" });
                }
                else
                {
                    Success = false;
                    if (result.Errors.Count() > 0)
                    {
                        foreach (var err in result.Errors)
                        {
                            if (err == "Incorrect password.")
                            {
                                Message = "Incorrect old password.";
                                break;
                            }
                            else
                            {
                                Message = err;
                                break;
                            }
                        }
                    }
                    //Message = "Password could not Match";
                }

            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }
            return Json(new
            {
                Success = Success,
                Message = Message
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("LogIn", "Account", new { area = "" });

        }


    }
}

Mylumineyes.Web/Areas/SuperAdmin/Views/Dashboard/ChangePassword.cshtml
@using Mylumineyes.Areas.SuperAdmin.Models;
@model ChangePasswordVM
@{
    ViewBag.Title = "Change Password";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_Layout.cshtml";
}
<section class="content-header row">
    <div class="col-md-4">
        <h3>
            Change Password
        </h3>
    </div>
    <div class="col-md-8">
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="javascript:void(0);"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="breadcrumb-item active">Change Password</li>
        </ol>
    </div>
</section>
<section class="content">
    <div class="box">
        <!-- /.box-header -->
        <div class="box-body wizard-content">
            <div class="steps clearfix">
                @*@using (Html.BeginForm("ChangePassword", "Manage", FormMethod.Post, new { @class = "form-horizontal", @area = "", role = "form" }))
                    {*@
                <form id="ChangePasswordAdmin" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <hr />
                    @*@Html.ValidationSummary("", new { @class = "text-danger" })*@
                    <div class="row">
                        <div class="col-md-3"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.OldPassword, new { @class = "control-label" })
                                    @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.OldPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        <div class="col-md-3"></div>
                        </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.NewPassword, new { @class = "control-label" })
                                @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.NewPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })

                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                    </div>

                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 pul">
                            <div class="form-group pull-right">

                                @*<input type="submit" value="Change password" class="btn btn-primary m-t-15 " />*@
                                <button type="submit" class="btn btn-primary">Change password</button>

                            </div>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </form>
            </div>



            <div></div>
        </div>
        <!-- /.box-body -->
    </div>

</section>

@section scriptRequired{
    <script src="~/Areas/SuperAdmin/Content/js/jquery-1.10.2.min.js"></script>
  <script src="~/Areas/SuperAdmin/Content/js/jquery.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery-ui.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/popper.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/bootstrap.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/raphael.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.sparkline.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.slimscroll.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/fastclick.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/template.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/sweetalert.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.dataTables.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/dataTables.bootstrap.min.js"></script>

}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on("submit", "form#ChangePasswordAdmin", function () {

                if ($("form#ChangePasswordAdmin").valid()) {
                    swal({
                        title: "...Wait",
                        text: "Please wait your request is processing...",
                        showConfirmButton: false,
                    });
                    var formdata = new FormData(this);

                    $.ajax({
                        chache: false,
                        async: false,
                        type: "POST",
                        url: "@Url.Action("ChangePassword", "Dashboard", new {@area="" })",
                        processData: false,
                        contentType: false,
                        data: formdata,
                        success: function (data) {
                            if (data.Success == true) {
                                ResetData();
                                swal("Update Successful", data.Message, "success");

                                //$("#CMSPageData").hide();
                            }
                            else {
                                ResetData();
                                swal("Unsuccessful", data.Message, "error");
                            }
                        }
                    });
                }
                return false;
            });

            function ResetData() {
                $("#OldPassword").val('');
                $("#NewPassword").val('');
                $("#ConfirmPassword").val('');
            }

        });

    </script>

}

Mylumineyes.Web/Areas/SuperAdmin/Views/Dashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_Layout.cshtml";
}

<section class="content-header row">
    <div class="col-md-4">
        <h3>
            Dashboard - Request List
        </h3>
    </div>
    <div class="col-md-8">
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="@Url.Action("DashBoard","DashBoard",new {@area="SuperAdmin" })"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            
        </ol>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">                       
                        <div class="col-3">
                            <div class="form-group">
                                <input type="date" id="dtFrom" name="dtTo" class="form-control datepicker" placeholder="Date From" />
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <input type="date" id="dtTo" name="dtTo" class="form-control datepicker" placeholder="Date To" />
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                <input type="button" id="btnSearch" class="btn btn-primary" value="Search" />
                            </div>
                        </div>                       
                    </div>
                </div>
                <div class="box-body" id="divData">
                    @{Html.RenderAction("SearchRequests", "Dashboard", new { @area = "SuperAdmin" });}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section scriptRequired{
    <script src="~/Areas/SuperAdmin/Content/js/jquery-1.10.2.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery-ui.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/popper.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/bootstrap.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/raphael.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/morris.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/chart.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.sparkline.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.slimscroll.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/fastclick.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/template.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/sweetalert.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/jquery.dataTables.min.js"></script>
    <script src="~/Areas/SuperAdmin/Content/js/dataTables.bootstrap.min.js"></script>
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            setActiveClass("fa-dashboard");
            loadDataTable();
            $(document).on("click", "#btnSearch", function () {
                loadList();
            });
        });
        function loadList() {
            swalShowWait();            
            $.ajax({
                chache: false,
                async: false,
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: "@Url.Action("SearchRequests", "Dashboard")",
                data: { "dtFrom": $("#dtFrom").val(), "dtTo": $("#dtTo").val()},
                success: function (data) {
                    $("#divData").html('');
                    $("#divData").html(data);
                    loadDataTable();
                    swalHideWait();
                }
            });
        }
        function DeleteRequest(id) {
            swal({
                title: "Confirm",
                text: "Are you sure? you want to delete this record?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes",
                cancelButtonText: "No",
                closeOnConfirm: false,
                closeOnCancel: true
            }, function (isConfirm) {
                swalShowWait();
                if (isConfirm) {
                    $.ajax({
                        chahce: false,
                        async: false,
                        data: { id: id},
                        url: "@Url.Action("DeleteRequest", "Dashboard")",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.Success) {
                                swal({
                                    title: "Successful",
                                    text: data.Message,
                                    type: "success",
                                    showConfirmButton: false,
                                    timer: 1000
                                })
                                loadList();
                            }
                        }
                    });
                }
            });
            return false;
        }
        
    </script>
}

Mylumineyes.Web/Areas/SuperAdmin/Views/Dashboard/_RequestData.cshtml
@using Mylumineyes.Web.Models
@model List<UserDataVM>

<style>
    .col-sm-12 {
        overflow-x: auto;
    }

    .eye-photo {
        max-width: 200px;
        max-height: 150px;
    }
</style>
<table id="tblBillsHistory" class="table table-bordered table-hover display nowrap margin-top-10 table-responsive" cellspacing="0">
    <thead>
        <tr>
            <th colspan="2">Images</th>
            <th>FullName</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Obeservations</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a title="Download" href="@Url.Action("Download","Dashboard",new {docId=item.Id,col="File1"})" download><p><img class="eye-photo" src="@item.File1" /></p></a>
                    </td>
                    <td>
                        <a title="Download" href="@Url.Action("Download","Dashboard",new {docId=item.Id,col="File2"})" download><p><img class="eye-photo" src="@item.File2" /></p></a>
                    </td>
                    <td>@item.FullName</td>
                    <td>@item.Email</td>
                    <td>@item.PhoneNo</td>

                    <td>@item.Obeservations</td>
                    <td>@String.Format("{0: dd MMM yyyy}", item.CreatedDate)</td>
                    <td>
                        <a href="javascript:void(0)" title="Delete" class="btn btn-sm btn-danger" onclick="return DeleteRequest('@item.Id');">
                            <i class="fa fa-close"></i>
                        </a>
                        @*<a target="_blank" href="@Url.Action("GenerateInvoice", "ManageBills", new { @area = "SuperAdmin", param1 = item.Id, param2= item.ResidentId })" title="Generate Invoice" class="btn btn-sm btn-primary">
                                Download Invoice
                            </a>*@
                    </td>
                </tr>
            }
        }
    </tbody>
</table>